Rename example binaries and add new test in github actions

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -31,3 +31,16 @@ jobs:
 
     - name: Run tests
       run: make test
+
+    - name: Run xv6
+      run: |
+        make
+        timeout 60 bash -c './target/release/rvemu-cli -k bin/xv6/kernel.bin -f bin/xv6/fs.img > out'
+        grep -q "init: starting sh" ./out > /dev/null
+        if [ $? -eq 0 ] ; then
+          echo "succeed to run xv6"
+          exit 0
+        else
+          echo "fail"
+          exit 1
+        fi
